name: ⭐ Feature request
description: Create a detailed request for a new feature.
title: "feat: "
labels: ["Feature request"]
body:
  - type: markdown
    attributes:
      value: |
        <p align="center">
          <!-- add logo later -->
          <br>
          Continuing the legacy of Vanced
        </p>


        # ReVanced Web Manager feature request

        Before creating a new feature request, please keep the following in mind:

        - **Do not submit a duplicate feature request**: You can review existing feature requests [here](https://github.com/ReVanced/revanced-web-manager//labels/Feature%20request).
        - **Review the contribution guidelines**: Make sure your feature request adheres to it. You can find the guidelines [here](https://github.com/ReVanced/revanced-web-manager/blob/main/CONTRIBUTING.md).
        - **Do not use the issue page for support**: If you need help or have questions, check out other platforms on [revanced.app](https://revanced.app).
  - type: textarea
    attributes:
      label: Feature description
      description: |
        - Describe your feature in detail
        - Add images, videos, links, examples, references, etc. if possible
        - Add the target application name in case you request a new patch
  - type: textarea
    attributes:
      label: Motivation
      description: |
        A strong motivation is necessary for a feature request to be considered.

        - Why should this feature be implemented? 
        - What is the explicit use case?
        - What are the benefits?
        - What makes this feature important?
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your feature request will be closed if you don't follow the checklist below.
      options:
        - label: This issue is not a duplicate of an existing feature request.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: The feature request is only related to ReVanced Web Manager
          required: true